// <auto-generated />
namespace Vidly_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fifthchangesinitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fifthchangesinitial));
        
        string IMigrationMetadata.Id
        {
            get { return "202212260849302_fifthchangesinitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
